### ISSUE TITLE
A display template is shown when chat app opens

### ISSUE THREAD

**Issue by j-ed** [owncloud/chat#141]
## Expected behavior

When you click on the chat app icon it should instantly open the application window.

## Actual behavior

When you click on the chat app icon a kind of display template is shown before the application window is shown.
![20140911_oc702_aufruf_chat_app](https://cloud.githubusercontent.com/assets/2572764/4263748/d7d9a6e2-3bfd-11e4-97a7-ede42514387d.jpg)

## Steps to reproduce

1.) Navigate to the Chat app 

#### Server Configuration

OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.26
ownCloud version: 7.0.2
Chat app: 0.2.1

#### Client Configuration

Browser: Firefox 32.0.1
Operating system: Windows 7

**Comment by LEDfan** [comment]
@j-ed can you test the latest version, and see if it works? Thanks!

**Comment by LEDfan** [comment]
4bc70fbdb4deb575c20b7e83ec0f0674a1aa9ebe

**Comment by LEDfan** [comment]
Solved in master

**Comment by j-ed** [comment]
@LEDfan Sorry, I've missed your last post. I've checked v0.4.0 which is looking fine now :+1:
