### ISSUE TITLE
no date-/time-stamp shown behind chat message

### ISSUE THREAD

**Issue by j-ed** [owncloud/chat#161]
## Expected behavior

A date-/time-stamp should be shown behind each chat to be able to see at what date/time a message has been written.

## Actual behavior

A date-/time-stamp is only shown behind an old chat message but without a date information. For newer chats no date-/time-stamp is shown behind chat messages at all.

## Steps to reproduce

1. Open the chat app an enter a chat message.
2. Check if a date-/time-stamp is displayed.

#### Server Configuration

OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.34
ownCloud version: 7.0.3
Chat App version: v0.2.1.10 (2014-11-23)

#### Client Configuration

Browser: Firefox 33.1.1
Operating system: Windows 7

**Comment by LEDfan** [comment]
@j-ed is this what you mean?
![schermafbeelding 2015-02-02 op 13 09 14](https://cloud.githubusercontent.com/assets/2996275/6000755/1f21340e-aae2-11e4-8844-9cb031fa558a.png)

I'll create a hove with the full date and time.

**Comment by LEDfan** [comment]
And the tipsy is added with 2f6c99edf280d9cd43aa447e275dd7f22352171b

**Comment by j-ed** [comment]
@LEDfan I've checked it with v0.4.0 on oC v8.0.3 and I can indeed see a time-stamp but only from the second posting onwards in a chat. The initial posting doesn't show a time-stamp at all. I've tested this twice with different counterparts and have seen it in both chats.
