### ISSUE TITLE
Small Design issues

### ISSUE THREAD

**Issue by LEDfan** [owncloud/chat#188]
Reported by @jancborchardt 
- [x] In the left sidebar, all the text should be left-aligned at the same point. Currently some text sticks out in the sidebar (the »derp«, »Add person« and »View files« in the selected group) as well as in the content: The »asdf« message by admin should be shifted to the right as all other messages as well
- [x] all entries need to be 44px high at least. That needs to be done in the sidebar for »Add person« and »View files« (you could put them next to each other to save space) as well as in the message list. If each message is 44px high, we also don’t need the dividing lines necessarily.
- [x] if the timestamp stays the same between 2 messages, no need to repeat it.
- [ ]  when looking through the chat it is hard to make out which message was written by whom. There should be some extra top and bottom whitespace between messages by other people. Or even see to play with putting the messages of yourself on the right (like TextSecure and iMessage do it)

Reported by @sorglos
- [x]  There's no need to show the online state at more than one place. It's okay in the left pane, unnecessary in the message pane. Another option is the display_name of an online user in _italic_.
- [ ] The own display_name in **bold** or display_name with different colors. (I prefer the first option.)
- [x]  All messages with the same indent as @jancborchardt stated above.

**Comment by jancborchardt** [comment]
Yeah, removing the online state is a good point.

And the dividing lines should go – instead use more vertical whitespace to divide message blocks by different people. Currently it’s the exact same height as the messages themselves and it’s difficult to see where your messages start and the ones of the other person end.

You forgot to increase the height of »Add person« and »View attached files«. They need to be 44px high as well, otherwise it looks very bunched together and is hard to click.

Also, the second line below the username in the left sidebar should show the las message that was written in the chat in half-grey. Can you add that @LEDfan?

Great work! :)

**Comment by LEDfan** [comment]
I made the buttons entry 44px height + centered all displaynames left of an avatar:
![screen shot 2015-01-10 at 07 57 09](https://cloud.githubusercontent.com/assets/2996275/5690715/4fdc5ba6-989e-11e4-9c8a-e17362c25e09.png)

**Comment by LEDfan** [comment]
> And the dividing lines should go – instead use more vertical whitespace to divide message blocks by different people. Currently it’s the exact same height as the messages themselves and it’s difficult to see where your messages start and the ones of the other person end.

>Also, the second line below the username in the left sidebar should show the las message that was written in the chat in half-grey.  

Is this what you mean?
![screen shot 2015-01-10 at 08 08 27](https://cloud.githubusercontent.com/assets/2996275/5690735/0c21c426-98a0-11e4-80c2-eb8954070ed2.png)

**Comment by jancborchardt** [comment]
In the last screenshot, there of course shouldn’t be that much padding between different messages of the same person. Otherwise things look fine. :)

**Comment by LEDfan** [comment]
@jancborchardt @jbtbnl I think I fixed the margin and height of the messages:
![schermafbeelding 2015-02-02 op 13 04 13](https://cloud.githubusercontent.com/assets/2996275/6000251/25b01fb6-aadc-11e4-8a5f-24e8b3d89a55.png)

**Comment by LEDfan** [comment]
Time is also fixed. Now the time is only shown when it's different than the time of the last msg.
![schermafbeelding 2015-02-02 op 13 09 14](https://cloud.githubusercontent.com/assets/2996275/6000317/c3c078fe-aadc-11e4-8a77-7fa424e86c81.png)

**Comment by jancborchardt** [comment]
There now is too little vertical padding between the messages of 2 different people. Increase that a bit and we’re good. :)

**Comment by LEDfan** [comment]
![schermafbeelding 2015-02-09 op 17 40 52](https://cloud.githubusercontent.com/assets/2996275/6110569/d5fb8cf6-b082-11e4-986e-8eeb2bcbf1e4.png)
@jancborchardt

**Comment by jancborchardt** [comment]
YES! Great stuff @LEDfan :)
