### ISSUE TITLE
installation howto ?!?!

### ISSUE THREAD

**Issue by hemaanjo** [owncloud/chat#196]
I've copied the Chat to oc/apps/chat and changed file properties as usual.

When triing to aktivate Chat in Owncloud (currnet Version) i got the following error:

An exception occurred while executing 'CREATE TABLE `oc_chat_och_push_messages` (`id` INT AUTO_INCREMENT NOT NULL, `sender` VARCHAR(64) NOT NULL, `receiver` VARCHAR(64) NOT NULL, `receiver_session_id` VARCHAR(64) NOT NULL, `command` MEDIUMTEXT NOT NULL, PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_chat_och_push_messages' already exists

What's going wrong?

**Comment by lunarok** [comment]
Hi,

Same I get this error. Badly, I get the idea to remove the app (desactivate, remove folder) and then delete the tables of chat app.
Bu then, if I install again I get another sql error

    An exception occurred while executing 'INSERT INTO `oc_chat_och_users_online`(`session_id`,`last_online`) VALUES(?,?)' with params ["$$$$$$$$$$$$$$$$$$$$$", 1422906521]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_chat_och_users_online' doesn't exist

I remove the chain and put $$$$$$$$$ instead

Owncloud 7.0.4 on Debian 7 with Nginx/PHP5.6 and MariaDB

**Comment by LEDfan** [comment]
Hi @hemaanjo @lunarok nice that you are testing the chat app!

@hemaanjo I think you have installed the app before? However pleas remove all tables of the Chat app. (https://github.com/owncloud/chat/wiki/FAQ#uninstall-chat-app)

@lunarok 
Can you remove all tables too? https://github.com/owncloud/chat/wiki/FAQ#uninstall-chat-app

**Comment by lunarok** [comment]
Hi,

So I remove the records in app_config : DELETE FROM oc_appconfig WHERE appid='chat';
As the other tables were already deleted.
Now I get this error complaining about a table integrity violation

  An exception occurred while executing ' INSERT INTO `oc_chat_och_users_in_conversation` ( `user`, `conversation_id`, `joined` ) VALUES ( ?, ?, ? )' with params [null, "CONV_ID_1423135408_96", 1423135408]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user' cannot be null

**Comment by LEDfan** [comment]
@lunarok which ownCloud version are you using? Are you using LDAP?

**Comment by lunarok** [comment]
@LEDfan : I think you point to a good direction, in fact I'm using LDAP backend (and Owncloud 7.0.4)

**Comment by LEDfan** [comment]
Unfortunately, there is a bug with the ContactsManager (which Chat depends on) in core with combination of LDAP. There is a fix for this: https://github.com/owncloud/core/pull/13819 . Normally this will be merged in ownCloud 8.1.

**Comment by lunarok** [comment]
Ok, thanks for the link. Do you think I can apply your modification on my lib/private/contacts/localaddressbook.php ?

**Comment by lunarok** [comment]
@LEDfan for information, I apply your patch linked on my installation, the app Chat is working now. I just want to give some feedback on your patch, worth it.

**Comment by LEDfan** [comment]
@lunarok great! Thanks for testing.

**Comment by LEDfan** [comment]
I'm closing this since inactivity of @hemaanjo. Please reopen if the problem reappears.
