### ISSUE TITLE
Limit amount of messages in initvar

### ISSUE THREAD

**Issue by LEDfan** [owncloud/chat#201]
- page loads faster
 - less queries

TODO:
 - make auto fetch for new messages

**Comment by LEDfan** [comment]
@jancborchardt @jbtbnl how many messages should be loaded at the first request?

**Comment by jancborchardt** [comment]
I guess the 10 most recent messages for each of the 10 most recent conversations would definitely be enough. Or is 100 messages on first request too much still? Then the last 5 messages of the 5 most recent conversations.

**Comment by LEDfan** [comment]
Implemented :)
