### ISSUE TITLE
converse.js for XMPP

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/chat#211]
Just found this pretty popular JS library for XMPP connections, maybe it’s useful for us @LEDfan: https://github.com/jcbrand/converse.js

**Comment by LEDfan** [comment]
Looks like Converse.js is a full XMPP client itself, together with a GUI. However this Chat app has already a GUI. 

Note that it's build on the same library as our XMPP backend.

I added it to the Resource page (https://github.com/owncloud/chat/wiki/Resources#xmpp)

**Comment by jancborchardt** [comment]
Ok, cool! :)
