### ISSUE TITLE
Move to Archive

### ISSUE THREAD

**Issue by aspdye** [owncloud/chat#235]
Because it is not longer in active development, i think owncloudarchive is the better organization for this repository :sweat_smile: 

cc @DeepDiver1975

**Comment by LEDfan** [comment]
Hi, I'm fine with moving this to the owncloudarchive.
This is currently not being developed nor being maintained and we are working on a better app.

What do you think @jancborchardt @karlitschek ?

**Comment by jancborchardt** [comment]
Yeah, totally makes sense since we have the new collaboration with JSXC now.

@DeepDiver1975 since @LEDfan gave his OK, can you move it to owncloudarchive?
